export interface Job {
    id: string;
    title: string;
    company: string;
    location: string;
    mode: 'Remote' | 'Hybrid' | 'Onsite';
    experience: 'Fresher' | '0-1' | '1-3' | '3-5';
    skills: string[];
    source: 'LinkedIn' | 'Naukri' | 'Indeed';
    postedDaysAgo: number;
    salaryRange: string;
    applyUrl: string;
    description: string;
}

export const jobs: Job[] = [
    {
        id: '1',
        title: 'SDE Intern',
        company: 'Razorpay',
        location: 'Bangalore',
        mode: 'Hybrid',
        experience: 'Fresher',
        skills: ['React', 'Node.js', 'TypeScript'],
        source: 'LinkedIn',
        postedDaysAgo: 1,
        salaryRange: '₹35k–₹50k/month Internship',
        applyUrl: 'https://razorpay.com/jobs/sde-intern',
        description: 'Join the engineering team to build scalable payment infrastructure. You will work closely with senior mentors on high-impact projects.'
    },
    {
        id: '2',
        title: 'Graduate Engineer Trainee',
        company: 'TCS',
        location: 'Pune',
        mode: 'Onsite',
        experience: 'Fresher',
        skills: ['Java', 'SQL', 'Spring Boot'],
        source: 'Naukri',
        postedDaysAgo: 3,
        salaryRange: '3–5 LPA',
        applyUrl: 'https://www.tcs.com/careers/get-program',
        description: 'Entry-level position for engineering graduates. You will undergo extensive training on enterprise technologies and work on global projects.'
    },
    {
        id: '3',
        title: 'Junior Backend Developer',
        company: 'Flipkart',
        location: 'Bangalore',
        mode: 'Hybrid',
        experience: '0-1',
        skills: ['Java', 'Microservices', 'Redis'],
        source: 'Indeed',
        postedDaysAgo: 0,
        salaryRange: '10–18 LPA',
        applyUrl: 'https://www.flipkartcareers.com/jobs/backend-dev-jr',
        description: 'Build robust backend services for Indias largest e-commerce platform. Focus on performance, scalability, and system reliability.'
    },
    {
        id: '4',
        title: 'Frontend Intern',
        company: 'Swiggy',
        location: 'Bangalore',
        mode: 'Remote',
        experience: 'Fresher',
        skills: ['React', 'CSS', 'Javascript'],
        source: 'LinkedIn',
        postedDaysAgo: 2,
        salaryRange: '₹30k–₹40k/month Internship',
        applyUrl: 'https://careers.swiggy.com/internships',
        description: 'Help us craft beautiful and intuitive user interfaces for the Swiggy app. Work with the latest frontend technologies in a fast-paced environment.'
    },
    {
        id: '5',
        title: 'Java Developer',
        company: 'Infosys',
        location: 'Mysore',
        mode: 'Onsite',
        experience: '0-1',
        skills: ['Java', 'Spring Boot', 'Hibernate'],
        source: 'Naukri',
        postedDaysAgo: 5,
        salaryRange: '4–7 LPA',
        applyUrl: 'https://www.infosys.com/careers/java-developer',
        description: 'Engage in developing end-to-end software solutions for global clients. Collaboration with cross-functional teams to deliver quality code.'
    },
    {
        id: '6',
        title: 'React Developer',
        company: 'CRED',
        location: 'Bangalore',
        mode: 'Hybrid',
        experience: '1-3',
        skills: ['React', 'Next.js', 'Tailwind'],
        source: 'Indeed',
        postedDaysAgo: 1,
        salaryRange: '15–25 LPA',
        applyUrl: 'https://careers.cred.club/jobs/react-engineer',
        description: 'Create high-performance web applications with a focus on exceptional user experience and design-led engineering.'
    },
    {
        id: '7',
        title: 'Python Developer',
        company: 'Zomato',
        location: 'Gurgaon',
        mode: 'Onsite',
        experience: 'Fresher',
        skills: ['Python', 'Django', 'PostgreSQL'],
        source: 'LinkedIn',
        postedDaysAgo: 4,
        salaryRange: '8–12 LPA',
        applyUrl: 'https://www.zomato.com/careers/python-dev',
        description: 'Develop and maintain backend services for Zomatos food delivery and dining platform. Strong problem-solving skills are essential.'
    },
    {
        id: '8',
        title: 'QA Intern',
        company: 'Freshworks',
        location: 'Chennai',
        mode: 'Hybrid',
        experience: 'Fresher',
        skills: ['Selenium', 'Testing', 'Python'],
        source: 'Naukri',
        postedDaysAgo: 2,
        salaryRange: '₹20k–₹35k/month Internship',
        applyUrl: 'https://www.freshworks.com/careers/qa-intern',
        description: 'Learn automated testing and ensure the quality of Freshworks suite of customer engagement products. Mentorship provided.'
    },
    {
        id: '9',
        title: 'Data Analyst Intern',
        company: 'PhonePe',
        location: 'Bangalore',
        mode: 'Hybrid',
        experience: 'Fresher',
        skills: ['SQL', 'Python', 'Tableau'],
        source: 'Indeed',
        postedDaysAgo: 1,
        salaryRange: '₹30k–₹45k/month Internship',
        applyUrl: 'https://www.phonepe.com/careers/data-intern',
        description: 'Derive insights from massive datasets to drive business decisions. Work with stakeholders across teams to provide data-driven solutions.'
    },
    {
        id: '10',
        title: 'Full Stack Developer',
        company: 'Zoho',
        location: 'Chennai',
        mode: 'Onsite',
        experience: '1-3',
        skills: ['React', 'Java', 'PostgreSQL'],
        source: 'LinkedIn',
        postedDaysAgo: 6,
        salaryRange: '8–15 LPA',
        applyUrl: 'https://www.zoho.com/careers/fullstack-dev',
        description: 'Responsible for designing and developing efficient code for Zoho products. You will work on both frontend and backend technologies.'
    },
    {
        id: '11',
        title: 'Java Developer',
        company: 'Wipro',
        location: 'Bangalore',
        mode: 'Hybrid',
        experience: '1-3',
        skills: ['Java', 'Microservices', 'AWS'],
        source: 'Naukri',
        postedDaysAgo: 7,
        salaryRange: '6–10 LPA',
        applyUrl: 'https://careers.wipro.com/java-roles',
        description: 'Contribute to the development of enterprise-level Java applications. Involvement in the full SDLC and cloud integrations.'
    },
    {
        id: '12',
        title: 'React Developer',
        company: 'Juspay',
        location: 'Bangalore',
        mode: 'Hybrid',
        experience: '0-1',
        skills: ['React', 'Functional Programming', 'PureScript'],
        source: 'Indeed',
        postedDaysAgo: 2,
        salaryRange: '12–18 LPA',
        applyUrl: 'https://careers.juspay.in/frontend-engineer',
        description: 'Work on cutting-edge payment products. We value strong logical thinking and a deep understanding of functional programming.'
    },
    {
        id: '13',
        title: 'Python Developer',
        company: 'Capgemini',
        location: 'Hyderabad',
        mode: 'Onsite',
        experience: '1-3',
        skills: ['Python', 'Cloud Operations', 'Docker'],
        source: 'LinkedIn',
        postedDaysAgo: 8,
        salaryRange: '7–12 LPA',
        applyUrl: 'https://www.capgemini.com/careers/python-role',
        description: 'Implement backend services and automation tools using Python. Collaboration within global teams across various industry domains.'
    },
    {
        id: '14',
        title: 'Data Analyst Intern',
        company: 'Paytm',
        location: 'Noida',
        mode: 'Hybrid',
        experience: 'Fresher',
        skills: ['Excel', 'SQL', 'Python'],
        source: 'Naukri',
        postedDaysAgo: 3,
        salaryRange: '₹15k–₹30k/month Internship',
        applyUrl: 'https://paytm.com/careers/intern-da',
        description: 'Support the data team with cleaning, processing, and analyzing financial data. Perfect for aspiring data professionals.'
    },
    {
        id: '15',
        title: 'Graduate Engineer Trainee',
        company: 'Cognizant',
        location: 'Coimbatore',
        mode: 'Onsite',
        experience: 'Fresher',
        skills: ['Testing', 'Java', 'Agile'],
        source: 'Indeed',
        postedDaysAgo: 5,
        salaryRange: '4–6 LPA',
        applyUrl: 'https://careers.cognizant.com/get-india',
        description: 'Join Cognizants digital transformation projects. You will receive mentorship and training in modern engineering practices.'
    },
    {
        id: '16',
        title: 'SDE Intern',
        company: 'Ola Cabs',
        location: 'Bangalore',
        mode: 'Onsite',
        experience: 'Fresher',
        skills: ['Go', 'Node.js', 'System Design'],
        source: 'LinkedIn',
        postedDaysAgo: 2,
        salaryRange: '₹40k–₹60k/month Internship',
        applyUrl: 'https://ola.careers/intern-sde',
        description: 'Work on high-concurrency mobility platforms. You will assist in core service development and operational scaling.'
    },
    {
        id: '17',
        title: 'Junior Backend Developer',
        company: 'Accenture',
        location: 'Pune',
        mode: 'Hybrid',
        experience: '0-1',
        skills: ['Node.js', 'Go', 'Kubernetes'],
        source: 'Naukri',
        postedDaysAgo: 4,
        salaryRange: '6–9 LPA',
        applyUrl: 'https://www.accenture.com/careers/backend-junior',
        description: 'Implement distributed systems and cloud infrastructure. Involvement in designing highly scalable and reliable services.'
    },
    {
        id: '18',
        title: 'Frontend Intern',
        company: 'Dream11',
        location: 'Mumbai',
        mode: 'Hybrid',
        experience: 'Fresher',
        skills: ['React', 'Redux', 'Canvas'],
        source: 'Indeed',
        postedDaysAgo: 1,
        salaryRange: '₹50k/month Internship',
        applyUrl: 'https://careers.dream11.com/internships-frontend',
        description: 'Build interactive gaming experiences for millions of users. Deep dive into React and complex state management.'
    },
    {
        id: '19',
        title: 'React Developer',
        company: 'Meesho',
        location: 'Bangalore',
        mode: 'Remote',
        experience: '1-3',
        skills: ['React Native', 'Android', 'iOS'],
        source: 'LinkedIn',
        postedDaysAgo: 3,
        salaryRange: '18–28 LPA',
        applyUrl: 'https://meesho.careers/mobile-dev',
        description: 'Lead mobile development for a democratized e-commerce platform. Focus on performance optimization for low-end devices.'
    },
    {
        id: '20',
        title: 'QA Intern',
        company: 'InMobi',
        location: 'Bangalore',
        mode: 'Hybrid',
        experience: 'Fresher',
        skills: ['Java', 'Appium', 'Rest Assured'],
        source: 'Naukri',
        postedDaysAgo: 2,
        salaryRange: '₹25k–₹40k/month Internship',
        applyUrl: 'https://www.inmobi.com/careers/intern-qa',
        description: 'Develop comprehensive test suites for mobile advertising technology. Involvement in continuous integration and delivery.'
    },
    {
        id: '21',
        title: 'Data Analyst Intern',
        company: 'Nykaa',
        location: 'Mumbai',
        mode: 'Onsite',
        experience: '0-1',
        skills: ['Python', 'R', 'PowerBI'],
        source: 'Indeed',
        postedDaysAgo: 4,
        salaryRange: '₹20k–₹35k/month Internship',
        applyUrl: 'https://careers.nykaa.com/jobs/da-intern',
        description: 'Analyze beauty and fashion consumer trends. Work with diverse data sources to create impactful reports.'
    },
    {
        id: '22',
        title: 'Graduate Engineer Trainee',
        company: 'IBM',
        location: 'Gurgaon',
        mode: 'Hybrid',
        experience: 'Fresher',
        skills: ['AI', 'Cloud', 'Containerization'],
        source: 'LinkedIn',
        postedDaysAgo: 9,
        salaryRange: '5–8 LPA',
        applyUrl: 'https://www.ibm.com/it-jobs/get-india',
        description: 'Embark on a career in AI and Hybrid Cloud. Extensive learning path provided through IBMs internal training programs.'
    },
    {
        id: '23',
        title: 'Full Stack Developer',
        company: 'Postman',
        location: 'Bangalore',
        mode: 'Remote',
        experience: '1-3',
        skills: ['Node.js', 'React', 'MongoDB'],
        source: 'Indeed',
        postedDaysAgo: 2,
        salaryRange: '20–35 LPA',
        applyUrl: 'https://www.postman.com/careers/fullstack-engineer',
        description: 'Develop features for the world-leading API platform. You will be part of a high-ownership, engineering-first culture.'
    },
    {
        id: '24',
        title: 'Java Developer',
        company: 'Dell',
        location: 'Bangalore',
        mode: 'Onsite',
        experience: '3-5',
        skills: ['Java', 'Spring Cloud', 'Oracle'],
        source: 'Naukri',
        postedDaysAgo: 10,
        salaryRange: '12–18 LPA',
        applyUrl: 'https://jobs.dell.com/java-senior-dev',
        description: 'Lead the development of backend services for enterprise hardware and software solutions. Mentorship of junior members included.'
    },
    {
        id: '25',
        title: 'React Developer',
        company: 'Shiprocket',
        location: 'Gautam Budh Nagar',
        mode: 'Hybrid',
        experience: '1-3',
        skills: ['React', 'Material UI', 'GraphGL'],
        source: 'LinkedIn',
        postedDaysAgo: 6,
        salaryRange: '10–16 LPA',
        applyUrl: 'https://careers.shiprocket.com/frontend-dev',
        description: 'Build sophisticated shipping and logistics management web applications. Deep involvement in frontend architecture and state.'
    },
    {
        id: '26',
        title: 'Python Developer',
        company: 'Urban Company',
        location: 'Gurgaon',
        mode: 'Hybrid',
        experience: '0-1',
        skills: ['Python', 'FastAPI', 'Redis'],
        source: 'Indeed',
        postedDaysAgo: 1,
        salaryRange: '12–20 LPA',
        applyUrl: 'https://careers.urbancompany.com/backend-eng',
        description: 'Power the services that enable home improvement and grooming. Work on high-performance routing and matching algorithms.'
    },
    {
        id: '27',
        title: 'Graduate Engineer Trainee',
        company: 'Oracle',
        location: 'Hyderabad',
        mode: 'Onsite',
        experience: 'Fresher',
        skills: ['C++', 'SQL', 'Algorithms'],
        source: 'Naukri',
        postedDaysAgo: 8,
        salaryRange: '8–14 LPA',
        applyUrl: 'https://www.oracle.com/careers/entry-dev',
        description: 'Develop core cloud infrastructure and database technologies. High bar for algorithmic excellence and system knowledge.'
    },
    {
        id: '28',
        title: 'Frontend Intern',
        company: 'Groww',
        location: 'Bangalore',
        mode: 'Hybrid',
        experience: 'Fresher',
        skills: ['React', 'Next.js', 'Chart.js'],
        source: 'Indeed',
        postedDaysAgo: 5,
        salaryRange: '₹30k–₹45k/month Internship',
        applyUrl: 'https://groww.in/careers/intern-frontend',
        description: 'Craft beautiful fintech dashboards. You will work on financial visualizations and high-traffic investment platforms.'
    },
    {
        id: '29',
        title: 'Graduate Engineer Trainee',
        company: 'SAP',
        location: 'Bangalore',
        mode: 'Hybrid',
        experience: 'Fresher',
        skills: ['Hana', 'ABAP', 'Java'],
        source: 'LinkedIn',
        postedDaysAgo: 7,
        salaryRange: '7–12 LPA',
        applyUrl: 'https://jobs.sap.com/india-trainee',
        description: 'Contribute to the worlds most prominent ERP software. Comprehensive training on SAP Hana platform and enterprise stacks.'
    },
    {
        id: '30',
        title: 'Junior Backend Developer',
        company: 'Udaan',
        location: 'Bangalore',
        mode: 'Onsite',
        experience: '0-1',
        skills: ['Kotlin', 'Java', 'RocksDB'],
        source: 'Naukri',
        postedDaysAgo: 4,
        salaryRange: '15–22 LPA',
        applyUrl: 'https://udaan.com/careers/backend-junior',
        description: 'Work on supply-chain and B2B commerce backend systems. You will solve complex distribution and logistical problems.'
    },
    {
        id: '31',
        title: 'SDE Intern',
        company: 'Hike',
        location: 'Remote',
        mode: 'Remote',
        experience: 'Fresher',
        skills: ['Unity', 'C#', 'Web3'],
        source: 'Indeed',
        postedDaysAgo: 1,
        salaryRange: '₹30k–₹50k/month Internship',
        applyUrl: 'https://hike.in/careers/intern-gaming',
        description: 'Join the Metaverse team at Hike. Work on immersive social experiences and cutting-edge gaming technology.'
    },
    {
        id: '32',
        title: 'React Developer',
        company: 'BigBasket',
        location: 'Bangalore',
        mode: 'Onsite',
        experience: '1-3',
        skills: ['React', 'Redux Saga', 'Sass'],
        source: 'LinkedIn',
        postedDaysAgo: 9,
        salaryRange: '10–18 LPA',
        applyUrl: 'https://careers.bigbasket.com/frontend-dev',
        description: 'Work on the frontend for the largest grocery store in India. Emphasis on search optimization and smooth mobile ordering.'
    },
    {
        id: '33',
        title: 'Java Developer',
        company: 'L&T Infotech',
        location: 'Chennai',
        mode: 'Hybrid',
        experience: '0-1',
        skills: ['Java', 'Spring MVC', 'Oracle'],
        source: 'Naukri',
        postedDaysAgo: 6,
        salaryRange: '4–7 LPA',
        applyUrl: 'https://www.lntinfotech.com/apply-java',
        description: 'Deliver enterprise software for global manufacturing and energy giants. Part of an agile, multi-cultural engineering team.'
    },
    {
        id: '34',
        title: 'QA Intern',
        company: 'Licious',
        location: 'Bangalore',
        mode: 'Onsite',
        experience: 'Fresher',
        skills: ['Manual Testing', 'Cypress', 'API'],
        source: 'Indeed',
        postedDaysAgo: 2,
        salaryRange: '₹15k–₹25k/month Internship',
        applyUrl: 'https://careers.licious.in/qa-intern',
        description: 'Verify the quality of supply chain apps. Learn end-to-end testing from farm to fork logistics ecosystems.'
    },
    {
        id: '35',
        title: 'Python Developer',
        company: 'Upstox',
        location: 'Mumbai',
        mode: 'Remote',
        experience: '1-3',
        skills: ['Python', 'Kafka', 'ElasticSearch'],
        source: 'LinkedIn',
        postedDaysAgo: 3,
        salaryRange: '14–22 LPA',
        applyUrl: 'https://upstox.com/careers/backend-developer',
        description: 'Optimize stock market execution and real-time streaming data services. Passion for high-concurrency systems required.'
    },
    {
        id: '36',
        title: 'Frontend Intern',
        company: 'PocketFM',
        location: 'Bangalore',
        mode: 'Hybrid',
        experience: 'Fresher',
        skills: ['React', 'Preact', 'Tailwind'],
        source: 'Naukri',
        postedDaysAgo: 5,
        salaryRange: '₹25k–₹40k/month Internship',
        applyUrl: 'https://pocketfm.com/careers/intern-fe',
        description: 'Help develop audio streaming platforms. Work on lightweight, highly optimized web players and discovery pages.'
    },
    {
        id: '37',
        title: 'Data Analyst Intern',
        company: 'Blinkit',
        location: 'Gurgaon',
        mode: 'Onsite',
        experience: 'Fresher',
        skills: ['Python', 'Pandas', 'Looker'],
        source: 'Indeed',
        postedDaysAgo: 1,
        salaryRange: '₹30k–₹45k/month Internship',
        applyUrl: 'https://blinkit.com/careers/data-intern',
        description: 'Help optimize 10-minute delivery loops. You will interpret real-time delivery and stock metrics to boost efficiency.'
    },
    {
        id: '38',
        title: 'Graduate Engineer Trainee',
        company: 'HCL Technologies',
        location: 'Noida',
        mode: 'Hybrid',
        experience: 'Fresher',
        skills: ['Networking', 'C', 'Embedded'],
        source: 'LinkedIn',
        postedDaysAgo: 10,
        salaryRange: '3.5–6 LPA',
        applyUrl: 'https://www.hcltech.com/careers/trainee',
        description: 'Dive into infrastructure and embedded systems development. You will handle large scale network monitoring tools.'
    },
    {
        id: '39',
        title: 'SDE Intern',
        company: 'Clear',
        location: 'Bangalore',
        mode: 'Hybrid',
        experience: 'Fresher',
        skills: ['Java', 'SQL', 'React'],
        source: 'Indeed',
        postedDaysAgo: 4,
        salaryRange: '₹35k–₹50k/month Internship',
        applyUrl: 'https://cleartax.in/careers/intern-sde',
        description: 'Build sophisticated tax-filing and compliance platforms. You will solve complex logic problems and data transformations.'
    },
    {
        id: '40',
        title: 'React Developer',
        company: 'Jupiter',
        location: 'Mumbai',
        mode: 'Remote',
        experience: '1-3',
        skills: ['React', 'React Native', 'TypeScript'],
        source: 'LinkedIn',
        postedDaysAgo: 2,
        salaryRange: '18–30 LPA',
        applyUrl: 'https://jupiter.money/careers/mobile-dev',
        description: 'Craft a Neobanking experience that people love. Work on intuitive financial apps with a design-first philosophy.'
    },
    {
        id: '41',
        title: 'Python Developer',
        company: 'Dunzo',
        location: 'Bangalore',
        mode: 'Hybrid',
        experience: '0-1',
        skills: ['Python', 'Golang', 'DynamoDB'],
        source: 'Naukri',
        postedDaysAgo: 3,
        salaryRange: '10–15 LPA',
        applyUrl: 'https://dunzo.com/careers/backend-engineer',
        description: 'Power the quick-commerce engine for daily essentials. Involvement with routing algorithms and delivery logistics.'
    },
    {
        id: '42',
        title: 'Java Developer',
        company: 'Mindtree',
        location: 'Bangalore',
        mode: 'Onsite',
        experience: '1-3',
        skills: ['Java', 'Angular', 'PostgreSQL'],
        source: 'Indeed',
        postedDaysAgo: 8,
        salaryRange: '6–11 LPA',
        applyUrl: 'https://www.mindtree.com/careers/java-job',
        description: 'Deliver full-stack web solutions for digital enterprise clients. Collaborative work in an agile, cloud-native environment.'
    },
    {
        id: '43',
        title: 'SDE Intern',
        company: 'CoinSwitch',
        location: 'Bangalore',
        mode: 'Hybrid',
        experience: 'Fresher',
        skills: ['Go', 'React', 'Cryptography'],
        source: 'LinkedIn',
        postedDaysAgo: 2,
        salaryRange: '₹40k–₹60k/month Internship',
        applyUrl: 'https://coinswitch.co/careers/intern-sde',
        description: 'Work on Indias largest crypto trading platform. Exposure to decentralized finance and high-concurrency order-books.'
    },
    {
        id: '44',
        title: 'QA Intern',
        company: 'Unacademy',
        location: 'Bangalore',
        mode: 'Onsite',
        experience: 'Fresher',
        skills: ['Automation', 'Load Testing', 'Appium'],
        source: 'Indeed',
        postedDaysAgo: 6,
        salaryRange: '₹20k–₹35k/month Internship',
        applyUrl: 'https://unacademy.com/careers/qa-intern',
        description: 'Support the quality of online learning apps. Focus on ensuring smooth video streaming and interactive live classes.'
    },
    {
        id: '45',
        title: 'React Developer',
        company: 'Spinny',
        location: 'Gurgaon',
        mode: 'Hybrid',
        experience: '1-3',
        skills: ['React', 'Firebase', 'Next.js'],
        source: 'LinkedIn',
        postedDaysAgo: 5,
        salaryRange: '12–20 LPA',
        applyUrl: 'https://www.spinny.com/careers/frontend-dev',
        description: 'Build web systems for car-buying and selling. You will create highly visual and interactive inventories for used vehicles.'
    },
    {
        id: '46',
        title: 'Data Analyst Intern',
        company: 'Cars24',
        location: 'Gurgaon',
        mode: 'Onsite',
        experience: 'Fresher',
        skills: ['Python', 'Looker', 'SQL'],
        source: 'Naukri',
        postedDaysAgo: 3,
        salaryRange: '₹25k–₹40k/month Internship',
        applyUrl: 'https://www.cars24.com/careers/intern-da',
        description: 'Analyze used car market valuations and customer preference patterns. Deep dive into supply-demand forecasting data.'
    },
    {
        id: '47',
        title: 'Java Developer',
        company: 'Tech Mahindra',
        location: 'Pune',
        mode: 'Hybrid',
        experience: '3-5',
        skills: ['Java 17', 'Kafka', 'Microservices'],
        source: 'Indeed',
        postedDaysAgo: 10,
        salaryRange: '12–22 LPA',
        applyUrl: 'https://careers.techmahindra.com/senior-java',
        description: 'Design and deploy scalable 5G and communication platform architectures in Java. Part of global telecom consulting projects.'
    },
    {
        id: '48',
        title: 'Graduate Engineer Trainee',
        company: 'Amazon India',
        location: 'Bangalore',
        mode: 'Hybrid',
        experience: 'Fresher',
        skills: ['Java', 'C++', 'Systems'],
        source: 'LinkedIn',
        postedDaysAgo: 1,
        salaryRange: '18–25 LPA',
        applyUrl: 'https://amazon.jobs/en/jobs/trainee-sde',
        description: 'Be part of the Amazon SDE-1 program. You will build and scale services that impact millions of sellers and customers.'
    },
    {
        id: '49',
        title: 'SDE Intern',
        company: 'Zerodha',
        location: 'Bangalore',
        mode: 'Remote',
        experience: 'Fresher',
        skills: ['Go', 'Postgres', 'Vue.js'],
        source: 'Indeed',
        postedDaysAgo: 0,
        salaryRange: '₹50k/month Internship',
        applyUrl: 'https://zerodha.tech/careers/intern-sde',
        description: 'Contribute to the technology stack that powers Indias #1 stock broker. We value simple, stable engineering over buzzwords.'
    },
    {
        id: '50',
        title: 'Junior Backend Developer',
        company: 'Delhivery',
        location: 'Gurgaon',
        mode: 'Onsite',
        experience: '0-1',
        skills: ['Python', 'Go', 'GCP'],
        source: 'Naukri',
        postedDaysAgo: 5,
        salaryRange: '12–18 LPA',
        applyUrl: 'https://www.delhivery.com/careers/backend-eng',
        description: 'Work on supply chain and logistical routing systems at scale. You will enhance the efficiency of Indias logistics backbone.'
    },
    {
        id: '51',
        title: 'Python Developer',
        company: 'Incedo',
        location: 'Chennai',
        mode: 'Hybrid',
        experience: 'Fresher',
        skills: ['Python', 'SQL', 'Automation'],
        source: 'LinkedIn',
        postedDaysAgo: 9,
        salaryRange: '4–7 LPA',
        applyUrl: 'https://incedoinc.com/careers/entry-python',
        description: 'Assist in data engineering and automation workflows for financial clients. Collaborative team environment in a modern workplace.'
    },
    {
        id: '52',
        title: 'Frontend Intern',
        company: 'ShareChat',
        location: 'Bangalore',
        mode: 'Remote',
        experience: 'Fresher',
        skills: ['React', 'Web Graphics', 'Wasm'],
        source: 'Indeed',
        postedDaysAgo: 2,
        salaryRange: '₹40k–₹55k/month Internship',
        applyUrl: 'https://sharechat.com/careers/intern-fe',
        description: 'Work on highly interactive social feed UI for millions of users. Optimized content delivery and rich media experiences.'
    },
    {
        id: '53',
        title: 'Graduate Engineer Trainee',
        company: 'Zensar',
        location: 'Pune',
        mode: 'Onsite',
        experience: 'Fresher',
        skills: ['Java', 'SQL', 'Testing'],
        source: 'Naukri',
        postedDaysAgo: 7,
        salaryRange: '3.5–5 LPA',
        applyUrl: 'https://zensar.com/careers/graduate-program',
        description: 'Learn enterprise software development through Zensars structured training and real-world project assignments.'
    },
    {
        id: '54',
        title: 'QA Intern',
        company: 'MakeMyTrip',
        location: 'Gurgaon',
        mode: 'Hybrid',
        experience: 'Fresher',
        skills: ['Java', 'Selenium', 'JMeter'],
        source: 'LinkedIn',
        postedDaysAgo: 0,
        salaryRange: '₹20k–₹35k/month Internship',
        applyUrl: 'https://careers.makemytrip.com/jobs/qa-intern',
        description: 'Help ensure the stability of Indias leading travel platform. You will work on test suites for booking and payment flows.'
    },
    {
        id: '55',
        title: 'React Developer',
        company: 'Acko',
        location: 'Bangalore',
        mode: 'Hybrid',
        experience: '1-3',
        skills: ['React', 'Lottie', 'Node.js'],
        source: 'Indeed',
        postedDaysAgo: 4,
        salaryRange: '15–25 LPA',
        applyUrl: 'https://www.acko.com/careers/frontend-engineer',
        description: 'Work on modern insurance purchase and claim flows. Priority on fast, seamless UI interactions and polished design.'
    },
    {
        id: '56',
        title: 'Data Analyst Intern',
        company: 'Khatabook',
        location: 'Bangalore',
        mode: 'Remote',
        experience: 'Fresher',
        skills: ['Python', 'SQL', 'Dash'],
        source: 'LinkedIn',
        postedDaysAgo: 1,
        salaryRange: '₹30k–₹45k/month Internship',
        applyUrl: 'https://khatabook.com/careers/intern-da',
        description: 'Analyze merchant behavior and credit cycles. Provide data support for SMB empowerment tools across India.'
    },
    {
        id: '57',
        title: 'Full Stack Developer',
        company: 'Mfine',
        location: 'Bangalore',
        mode: 'Hybrid',
        experience: '0-1',
        skills: ['React', 'Express', 'Pytorch'],
        source: 'Naukri',
        postedDaysAgo: 3,
        salaryRange: '10–18 LPA',
        applyUrl: 'https://www.mfine.co/careers/fullstack-eng',
        description: 'Develop healthcare platforms connecting doctors and patients. Work on health monitoring and scheduling tech stacks.'
    },
    {
        id: '58',
        title: 'SDE Intern',
        company: 'Curefit',
        location: 'Bangalore',
        mode: 'Onsite',
        experience: 'Fresher',
        skills: ['Swift', 'Angular', 'Java'],
        source: 'Indeed',
        postedDaysAgo: 2,
        salaryRange: '₹35k–₹55k/month Internship',
        applyUrl: 'https://cult.fit/careers/intern-sde',
        description: 'Work on health and fitness apps. Exposure to highly scalable fitness class management and digital workout platforms.'
    },
    {
        id: '59',
        title: 'Junior Backend Developer',
        company: 'Pharmeasy',
        location: 'Mumbai',
        mode: 'Hybrid',
        experience: '0-1',
        skills: ['Python', 'Redis', 'AWS'],
        source: 'LinkedIn',
        postedDaysAgo: 4,
        salaryRange: '12–18 LPA',
        applyUrl: 'https://pharmeasy.in/careers/backend-junior',
        description: 'Help build Indias largest medicine delivery platform. Focus on logistics optimization and inventory management backend.'
    },
    {
        id: '60',
        title: 'Frontend Intern',
        company: 'Uniphore',
        location: 'Chennai',
        mode: 'Onsite',
        experience: 'Fresher',
        skills: ['React', 'WebRTC', 'D3.js'],
        source: 'Naukri',
        postedDaysAgo: 6,
        salaryRange: '₹25k–₹40k/month Internship',
        applyUrl: 'https://www.uniphore.com/careers/intern-fe',
        description: 'Work on conversational AI platforms. You will assist in rendering complex speech analytics and real-time dashboards.'
    }
];
